import { z } from "zod/v4";

const paymentMethodEnum = z.enum(["bkash", "nagad"]);
const escrowStatusEnum = z.enum([
  "awaiting_payment",
  "funds_held",
  "item_delivered",
  "buyer_confirmed",
  "released",
  "disputed",
  "refunded",
  "cancelled",
  "auto_released",
]);

export const initiateTradeSchema = z.object({
  listing_id: z.string().uuid("Invalid listing ID"),
});

export const fundTradeSchema = z.object({
  payment_method: paymentMethodEnum,
  payment_reference_id: z.string().min(1, "Payment reference ID is required"),
  /**
   * Idempotency key to safely handle duplicate /fund requests.
   * Generated by the frontend before sending the request.
   * If the same key is received twice, the second request is silently ignored.
   */
  idempotency_key: z.string().uuid("Idempotency key must be a valid UUID"),
});

export const deliverTradeSchema = z.object({
  proof_screenshot_url: z.string().url("Proof screenshot must be a valid URL").optional().nullable(),
  /** Optional note from seller to buyer */
  delivery_note: z.string().max(500).optional().nullable(),
});

export const confirmTradeSchema = z.object({
  /** Optional note from buyer */
  note: z.string().max(500).optional().nullable(),
});

export const disputeTradeSchema = z.object({
  reason: z.string().min(10, "Please provide a detailed reason for the dispute").max(2000),
});

export type InitiateTradeInput = z.infer<typeof initiateTradeSchema>;
export type FundTradeInput = z.infer<typeof fundTradeSchema>;
export type DeliverTradeInput = z.infer<typeof deliverTradeSchema>;
export type ConfirmTradeInput = z.infer<typeof confirmTradeSchema>;
export type DisputeTradeInput = z.infer<typeof disputeTradeSchema>;